verb1 = input("enter a verb in participle form (+ing form):     "  )
noun1 = input(" enter a living thing:    ")
verb2 = input("enter a verb, preferably a request:     ")
place1 = input("enter a place:    ")
verb3 = input("enter a verb again:     ")
print("you were " + verb1+ " in your street. A " + noun1 +  " came to you and asked to " + verb2 +  ". You agreed to it, both of you went to a " + place1 + " to " + verb2 + ". Then you two decided to " + verb3 + ".")