var1= input("type a noun:   ")
var2 = input("type a wacky state:    ")
var3 = input("type a verb :    ")
var4= input("type a noun :    ")
v5 = input("type a proper name :    ")
v6= input("type a verb :    ")
v7 = input("type a noun :    ")
v8 = input("type a verb :    ")
v9 = input("type a noun :    ")
v10 = input("type a part of body:    ")
v11 = input("type an adjective:    ")
v12 = input("type a relative :    ")
v13 = input("type a activity :    ")
v14= input("type a chain restraunt:    ")
v15 = input("type a verb(past form):    ")
v16 = input("type a month:    ")
v17 = input("type a verb :    ")
v18 = input("type a noun :    ")
v19 = input("type a verb in past :    ")
v20 = input("type an adjective:    ")
v21 = input("type a verb :    ")
v22 = input("type a thing :    ")
v23 = input("type a plural noun :    ")
#verb1 = input("type a verb :    ")
#verb1 = input("type a verb :    ")
#verb1 = input("type a verb :    ")
print("A " + var1 + " in " + var2 + "state was arrested this morning after he " + var3 + " in front of " + var4 + ". " + v5 + ", had a history of " + v6 + ", but no-one, not even his " + v7 +" ever imagined he'd " + v8 +" with a " + v9 + " stuck in his " + v10 + ".")

print("\" I always thought he was " + v11 + ", but I  never thought he'd do something like this. Even his " + v12 + " was surprised\"")

print("After a brief " + v13 + ", cops followed him to a " + v14 + ", where he reportedly " + v15+ " in the fry machine.")

print("In " +v16+ ", a woman was charged with a similar crime. But rather than " +v17+ " with a " + v18 + ", she " + v19 + " with a " + v20 + " dog.")

print("Either way, we imagine that after witnessing him " + v21 + " with a " + v22 + " there are probably a whole lot of " + v23 + "that are going to need some therapy")
